### ISSUE TITLE
How can we spin up the mongodb-memory-server only for the tests that depend on DB?

### ISSUE THREAD

**Issue by htbkoo** [vladgolubev/jest-mongodb#19]
First of all, thanks so much for creating this repo example - I had been trying for days and it is really helpful and appreciated.

However, I wonder if there is any way to configure it so that the mongodb-memory-server is only started up when we are running the tests / test suites that would depend on DB connection (e.g. usually the slower tests such as integration tests), but not when only unit tests are run?

FYI, currently I am grouping my tests into the unit tests (run more frequently for faster feedback) and integration tests (slower and thus are run less frequently)

**Comment by vladgolubev** [comment]
@htbkoo  for that scenario I suggest using jest projects - https://jestjs.io/docs/en/configuration#projects-array-string-projectconfig

You can setup different jest environment, test file pattern, etc for different kind of tests

Hope it helps you!

**Comment by htbkoo** [comment]
Thanks, will check it out. 👍

**Comment by htbkoo** [comment]
Thanks for the suggestion - it works (I ended up doing something in slightly different way using multiple jest configs to suit my own needs but it guided me towards the correct path).

Closing this now. :-)
